export const goodGreetings = [
  "Oye Unisha 😏",
  "K xa timro mood?",
  "Ramri dekhinchau aajaa ✨",
  "Din ramro jaos 🙏",
  "Timi ta sahi chau 😄",
  "Khusi lagyo timi herda",
  "Aja kasto feel cha?",
  "Screen bright bhayo timi herda 💫",
  "Mood fresh cha ajha 😄",
  "Timi ta genuine chau 🩷",
  "Aaja fresh lagchau timi 😇",
  "Timi herera ramro lagyo 😄",
  "Timro naam bhaye ni smile ayo 😏",
  "Oye, ajha cute lagchau 😌",
  "Yo smile ta wow 🙂",
  "Mood ta bright bhayo 😎",
  "Timi inspiration chau 😇",
  "Day ta ramailo lagyo 😄",
  "Timi sunshine jasto chau 🌞",
  "Timi ko energy mast 😎",
  "Yo laughter cute cha 🙂",
  "Timi pura highlight chau 😇",
  "Timi ta awesome chau 😄",
  "Smile le sab thik 😎",
  "Timi ta chill ho 🙂",
  "Yo vibe khusi cha 😄",
  "Timi ta brilliant chau 🌟",
  "Mood ta glow bhayo 😎",

  // English
  "You rock today 🙂",
  "Smile brightens all 😄",
  "Such chill vibes 😎",
  "You inspire today 😇",
  "Day feels lighter 🙂",
  "You shine bright 🌟",
  "Joyful energy here 😄",
  "Mood lifted now 😎",
  "Such pure vibe 🙂",
  "You brighten room 😄",
  "Happy day ahead 😎",
  "Your laugh magic 🙂",
  "Such calm energy 😄",
  "You light up space 🌟",
  "Nice vibes today 😎",
];

export const badGreetings = [
  "Oye! kon hey? 😅",
  "Kya hua? 😏",
  "Yo naam funny lagcha 😂",
  "Fake Unisha detected 😹",
  "Cat le ignore garyo 🙀",
  "Error 404: Unisha missing 😆",
  "System confuse bhayo 🤔",
  "Timi impostor jasto 😏",
  "Yo naam dherai sus 😜",
  "Aba cat hiss garyo 🐱💢",
  "Try feri gara 😅",
  "Not Unisha? Haha 😹",
  "Yo ta random entry 😆",
  "Typo ta ho ni 😏",
  "Name check gara 😬",
  "Cat pani confuse bhayo 😼",
  "Fake alert! 😂",
  "Oye hacker? 😅",
  "Wrong input! 😹",
  "Haha aba error 😆",
  "Suspicious lagyo 😏",
  "Access denied 😜",
  "Yo entry unusual 😆",
  "Cat roll eyes 🙀",
  "Fake naam detected 😅",
  "Oops! try again 😹",
  "Timi cheeky 😏",
  "Not authorized 😂",
  "Random username spotted 😝",
  "Haha meow confused 😼",
  "Yo ta full drama 😹",
  "Ab toh lagi error 😆",
  "Suspicious activity 😏",
  "Haha system roars 😂",
  "Check your name 😹",
  "Oops, wrong choice 😅",
  "Kya chal raha? 😄",
  "Oye, kon hey? 😅",
  "Kya kar rahe ho? 😹",
  "Abey yeh kaun? 😆",
  "Haha, kya ho yeh? 😝",
  "Timi ta slow ho 😝",
  "Yo move confuse garayo 😏",
  "Barca fan ho tara goal miss 😹",
  "PSG style missing 😆",
  "Chelsea ko defense weak 😏",
  "Timi ta late aayo 😅",
  "Cat ko reaction better ho 🐱",
  "Yo pass offside 😝",
  "Haha, tyo dribble fail 😹",
  "Timi ta distraction ho 😏",
  "Goal miss ta bhayo 😂",
  "Timi overthink garcha 😝",
  "Story update ta slow 😅",
  "Timi ta hype ho ni 😏",
  "Filter ta confuse bhayo 😹",
  "Post ta dull lagyo 😆",
  "Aja mood thik cha? 😏",
  "Timi ta sleepy lagchau 😴",
  "Haha, tyo move weak 😝",
  "Yo ta pura suspense 😹",
  "Followers pani confuse 😅",
  "Timi ta drama ho 😏",
  "Emoji ta missing cha 😹",
  "Haha, caption ta weak 😆",
  "Yo ta meme repeat 😝",
  "Timi ta offside ho 😏",
  "Haha, tyo shot miss 😹",
  "Timi ta substitute player ho ni 😅",
  "Goalkeeper pani confuse 😆",
  "Yo ta pura highlight 😝",
  "Timi ta tension ho 😏",
  "Haha, replay pani funny 😹",
  "Timi ta trend follower 😎",
  "Yo ta pura scene 😂",
  "Comment delete bhayo 😹",
  "Timi chai distraction 😏",
  "Ball miss bhayo 😹",
  "Timi ta slow ho 😅",
  "Story ta loop ma cha 😆",
  "Oye kya scene hai? 😏",
  "Arre yeh kaun hai? 😂",
  "Tera naam funny lagta 😝",
  "Kya kar raha hai bro? 😹",
  "Hahaha, full drama hai 😆",
  "Tu hero ya zero? 😏",
  "Abey yeh kya ho gaya? 😅",
  "Tera style mast hai 😎",
  "Bro, move thoda weak 😹",
  "Oye, kya chal raha? 😆",
  "Arre tension kyun le? 😝",
  "Tu late ho bhai 😏",
  "Kya yaar, miss ho gaya 😹",
  "Tu confuse lagta hai 😅",
  "Hahaha, full masti hai 😝",
  "Abey kya chal raha 😹",
  "Tera vibe mast hai 😎",
  "Oye, offside ho gaya 😂",
  "Bro, pass ta weak 😝",
  "Hahaha, full drama scene 😹",
  "Oye, fake naam hai 😏",
  "Tu hero nahi lagta 😹",
  "Hahaha, style ta fail 😆",
  "Kya yaar, score miss 😝",
  "Abey yeh kya scene? 😂",
  "Oye, last moment fail 😹",
  "Bro, mood off lagta 😏",
  "Hahaha, tension nahi lene 😝",
  "Kya yaar, cat confuse 😹",
  "Oye, viral moment miss 😎",
];
