export const goodGreetings = [
  "O Unisha",
  "K xa timro mood?",
  "Ramri dekhinchau aajaa ✨",
  "Din ramro jaos 🙏",
  "Timi ta sahi chau 😄",
  "Khusi lagyo timi herda",
  "Aja kasto feel cha?",
  "Screen bright bhayo timi herda 💫",
  "Mood fresh cha ajha 😄",
  "Timi ta genuine chau 🩷",
  "Timro naam bhaye ni smile ayo 😏",
  "Oye, ajha cute lagchau 😌",
  "Yo smile ta wow 🙂",
  "Mood ta bright bhayo 😎",
  "Timi inspiration chau 😇",
  "Day ta ramailo lagyo 😄",
  "Timi sunshine jasto chau 🌞",
  "Timi ko energy mast 😎",
  "Yo laughter cute cha 🙂",
  "Timi pura highlight chau 😇",
  "Timi ta awesome chau 😄",
  "Smile le sab thik 😎",
  "Timi ta chill ho 🙂",
  "Yo vibe khusi cha 😄",
  "Timi ta brilliant chau 🌟",
  "Mood ta glow bhayo 😎",

  // English
  "You rock today 🙂",
  "Smile brightens all 😄",
  "Such chill vibes 😎",
  "You inspire today 😇",
  "Day feels lighter 🙂",
  "You shine bright 🌟",
  "Joyful energy here 😄",
  "Mood lifted now 😎",
  "Such pure vibe 🙂",
  "You brighten room 😄",
  "Happy day ahead 😎",
  "Your laugh magic 🙂",
  "Such calm energy 😄",
  "You light up space 🌟",
  "Nice vibes today 😎",
];

export const badGreetings = [
  "Oye! kon hey? 😅",
  "Kya hua? 😏",
  "Fake Unisha detected 😹",
  "Timi impostor jasto 😏",
  "Try feri gara 😅",
  "Not Unisha? Haha 😹",
  "Yo ta random entry 😆",
  "Name check gara 😬",
  "Fake naam detected 😅",
  "Random username spotted 😝",
  "Yo ta full drama 😹",
  "Ab toh lagi error 😆",
  "Suspicious activity 😏",
  "Haha system roars 😂",
  "Check your name 😹",
  "Kya chal raha? 😄",
  "Oye, kon hey? 😅",
  "Kya kar rahe ho? 😹",
  "Abey yeh kaun? 😆",
  "Haha, kya ho yeh? 😝",
  "Timi ta slow ho 😝",
  "Barca fan ho tara goal miss 😹",
  "PSG style missing 😆",
  "Chelsea ko defense weak 😏",
  "Timi ta late aayo 😅",
  "Yo pass offside 😝",
  "Haha, tyo dribble fail 😹",
  "Goal miss ta bhayo 😂",
  "Filter ta confuse bhayo 😹",
  "Timi ta drama ho 😏",
  "Haha, caption ta weak 😆",
  "Haha, tyo shot miss 😹",
  "Timi substitute player 😅",
  "Goalkeeper pani confuse 😆",
  "Yo ta pura highlight 😝",
  "Timi ta tension ho 😏",
  "Timi ta trend follower 😎",
  "Ball miss bhayo 😹",
  "Oye kya scene hai? 😏",
  "Arre yeh kaun hai? 😂",
  "Tera naam funny lagta 😝",
  "Kya kar raha hai bro? 😹",
  "Hahaha, full drama hai 😆",
  "Abey yeh kya ho gaya? 😅",
  "Bro, move thoda weak 😹",
  "Oye, kya chal raha? 😆",
  "Arre tension kyun le? 😝",
  "Tu late ho bhai 😏",
  "Kya yaar, miss ho gaya 😹",
  "Tu confuse lagta hai 😅",
  "Hahaha, full masti hai 😝",
  "Abey kya chal raha 😹",
  "Tera vibe mast hai 😎",
  "Oye, offside ho gaya 😂",
  "Bro, pass ta weak 😝",
  "Hahaha, full drama scene 😹",
  "Oye, fake naam hai 😏",
  "Tu hero nahi lagta 😹",
  "Hahaha, style ta fail 😆",
  "Kya yaar, score miss 😝",
  "Abey yeh kya scene? 😂",
  "Oye, last moment fail 😹",
  "Bro, mood off lagta 😏",
  "Hahaha, tension nahi lene 😝",
  "Kya yaar, cat confuse 😹",
  "Oye, viral moment miss 😎",
];
